### PR TITLE
Added handling of attr_encrypted attributes.

### PR DESCRIPTION
**Pull request by saghaulor**
- The import method calls the model accessors in preparation for the raw SQL
  statements. This is bad news for encrypted columns as attr_encrypted
  rewrites accessors to do crypto operations. If we use the attr_reader
  of encrypted columns we'll decrypt the attribute, effectively never
  encrypting. Now we use read_attribute in the case of encrypted columns so
  that we store the cipher string.

### CODE REVIEW

**Comment by saghaulor** [comment]
- [ ] @shosti please review

**Comment by shosti** [comment]
lgtm :thumbsup:

**Comment by saghaulor** [comment]
Per a conversation with @shosti we should fix this implementation specific problem in our implementation of attr_encrypted, not in activerecord-import.

**Comment by saghaulor** [comment]
- [ ] @mikewagner please review.

**Pull request merged**
